services:
  - type: web
    name: notify-mock-service
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
